version: '3'
services:
  webserver:
    container_name: apiserver
    build: ./API/   
    depends_on:
      - database    
    ports:
      - "3001:3001"   
    environment:
      API: 172.18.0.4
      DB: 172.18.0.2
    networks:
      redapp:
        ipv4_address: 172.18.0.4 
  database:
    container_name: database
    image: mongo  
    ports:
      - "3000:27017"
    volumes:
      - ./mongo:/data/db
      
    environment:
      API: 172.18.0.4
      DB: 172.18.0.2
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      redapp:
        ipv4_address: 172.18.0.2 
 
networks:
  redapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
